### ISSUE TITLE
support env config

### ISSUE THREAD

**Issue by atian25** [kavod-io/vscode-jest-test-adapter#126] opened 2021-06-16 02:57 UTC
**Things to consider before raising a bug**
This extension needs to understand how your project(s) are structured, where to find your test configuration and test files among other things.  It turns out that there are many ways to structure JS projects and the extension may not currently accommodate your project.  The following section is to aid in collecting information to identify the issue.

**Describe the bug**
- [ ] test load missing suites/tests
- [ ] test load errors
- [ ] test running errors

**To Reproduce**

1. Write ESM modules
2. Run Test by plugin

**Expected behavior**

work fine just like `NODE_OPTIONS=--experimental-vm-modules jest`

**Comment by grigoreme** [comment] 2021-06-17 06:40
Have the same issue. Hope to have this feature.

**Comment by atian25** [comment] 2021-06-17 06:44
https://github.com/kavod-io/vscode-jest-test-adapter/blob/master/src/JestSettings/index.ts#L58

```js
return {    
  // need to provide a vscode settings then convert to nodeEnv
  nodeEnv: {},

  localJestMajorVersion: 20,    
  pathToConfig,   
  jestCommandLine: jestCommand,    
  rootPath: projectConfig.jestExecutionDirectory,  
};
```

**Comment by charles-allen** [comment] 2021-11-24 10:57
FYI, I think this is a dupe of #93

**Closed** 2022-11-12 05:55 UTC
