### ISSUE TITLE
Question: Possible to set custom config file?

### ISSUE THREAD

**Issue by basickarl** [kavod-io/vscode-jest-test-adapter#130] opened 2021-07-12 09:10 UTC
More a question than a bug config. Is it currently possible for Test Explorer to use a specific config file of my choosing? Or does the configuration file have to live in the default location?

**Comment by swkim0572** [comment] 2021-08-23 10:23
I need --config option too

**Comment by marknorrapscm** [comment] 2021-09-09 13:52
This is a duplicate of #125.

**Closed** 2024-03-13 19:42 UTC
